name: Playwright Tests for eShop
on:
  push:
    branches: [ test ]
    paths-ignore:
      - '**.md'
      - 'src/ClientApp/**'
      - 'tests/ClientApp.UnitTests/**'
      - '.github/workflows/pr-validation-maui.yml'
  pull_request:
    branches: [ test ]
    paths-ignore:
      - '**.md'
      - 'src/ClientApp/**'
      - 'test/ClientApp.UnitTests/**'
      - '.github/workflows/pr-validation-maui.yml'
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Add .NET tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Install system dependencies for Playwright
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libatspi2.0-0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxrandr2 \
          libgbm1 \
          libxkbcommon0 \
          libpango-1.0-0 \
          libcairo2 \
          libasound2

    - name: Install npm dependencies
      run: npm ci
    - name: Install .NET HTTPS Development Certificate
      # if: matrix.os == 'ubuntu-latest'
      run: |
        dotnet tool update -g linux-dev-certs
        dotnet linux-dev-certs install
    - name: Install Playwright Browsers
      run: npx playwright install chromium

    - name: Debug curl server
      run: |
        echo "Testing with curl..."
        curl -vk http://localhost:19888/ || true

    - name: Run Playwright tests
      run: npx playwright test --reporter=list
      env:
        ESHOP_USE_HTTP_ENDPOINTS: 1
        USERNAME1: bob
        PASSWORD: Pass123$
        DEBUG: pw:webserver*
        PWDEBUG: 1
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
